### ISSUE TITLE
libcloudproviders support

### ISSUE THREAD

**Issue by returntrip** [flathub/com.nextcloud.desktopclient.nextcloud#6] opened 2019-11-06 11:29 UTC
@juliushaertl is it technically possible to integrate [libcloudproviders](https://blog.juliushaertl.de/index.php/2017/08/28/gsoc-final-report/) for better shell integration? I guess it is not possible cause of flatpak sandboxing but worth asking the experts :).

I can use Topicons Plus to display the icon but that is not really how NC should integrate in Gnome 3. Plus I need to `flatpak override --nosocket=wayland org.nextcloud.Nextcloud` to have the icon display on Fedora Silverblue.

**Comment by tintou** [comment] 2023-09-06 13:43
FYI, I just released libcloudproviders 0.3.3 which should solve this issue once added to the client upstream.

**Comment by tintou** [comment] 2023-11-08 10:41
https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/121 has been merged, with the right libcloudproviders version on your system it should work out of the box now

**Closed** 2023-11-08 11:20 UTC
Labels: enhancement

**Comment by ekasprzak** [comment] 2024-02-07 14:52
Hi, should this "just work" with Fedora 39 (GNOME/Nautilus 45 + libcloudproviders 0.3.5) and most recent Flatpak's NC Desktop (3.11)?

If it should, what can I check in my env if it doesn't work (showing sync status of files/folders in nautilus) ?

**Comment by tintou** [comment] 2024-02-07 15:09
Yes it should just work, note that it will only add an entry in the location sidebar, not emblems to files

**Comment by ekasprzak** [comment] 2024-02-07 15:16
Oh, ok, thanks for the explanation.

Do you know if there are any plans to have status emblems in folders/file?
Or maybe this is not possible with flatpak/sandboxing at all?

**Comment by p-fruck** [comment] 2024-08-13 16:57
@ekasprzak This is possible with a bit of manual work. I spent some time today getting it to work and created a small write-up here: https://gist.github.com/p-fruck/6ec354da8fb348c19cca013c6c64df76

The issue is that nautilus does not run as a flatpak and therefore needs the nextcloud extension on the host.
